config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'comments/index'
  get 'comments/show'
  get 'comments/new'
  get 'comments/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/destroy'
  get 'posts/show'
  get 'posts/new'
  get 'posts/destroy'
  get 'posts/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def destroy
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]
    def index
        # @docs = Doc.all.order('created_at DESC')
        @docs = Doc.where(user_id: current_user)
    end
    def show
 
    end
    def new
        # @doc = Doc.new
        @doc = current_user.docs.build
    end
    def create
        # @doc = Doc.new(doc_params)
        @doc = current_user.docs.build(doc_params)
        if(@doc.save)
            redirect_to @doc
        else
            render 'new'
        end
    end
    def edit
    end
    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end    
    end
    def destroy
        @doc.destroy
        redirect_to docs_path
    end

    private

        def find_doc
            @doc = Doc.find(params[:id])
        end
        def doc_params
            params.require(:doc).permit(:title, :content)
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  end

  def new
  end

  def destroy
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/docs/_form.html.erb
<%= simple_form_for @doc, defaults: { input_html: { class: 'default_class' } } do |f| %>
    <%= f.input :title, input_html: { class: 'special' } %>
    <%= f.input :content, input_html: { maxlength: 200 } %>
    <%= f.button :submit %>
  <% end %>

app/views/docs/edit.html.erb
<h1>Edit doc</h1>

<%= render 'form' %>

<%= link_to "Cancel", doc_path %>

app/views/docs/index.html.erb
<div class="container">
<% unless @docs.blank? %>
<% @docs.each do |d| %>
<div class="row">
    <h1><%= link_to d.title, d %></h1>
    <small><%= time_ago_in_words(d.created_at) %></small>
    <p><%= truncate(d.content, length:50) %></p>
</div>
<% end %>
<% end %>
<%= link_to "New document?", new_doc_path %>
</div>

app/views/docs/new.html.erb
<h1>new doc</h1>

<%= render 'form' %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>
<p><%= @doc.content %></p>

<%= link_to "All docs", docs_path %>
<%= link_to "Fix doc", edit_doc_path(@doc) %>
<%= link_to "Trash it", doc_path(@doc), method: :delete, data: { "confirm": "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App :: Yes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% link_to "CabinetFiles", root_path %>
  <% if user_signed_in? %>
    <%= link_to "Create doc", new_doc_path %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "CabinetFiles", new_user_session_path %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
sssss
    <%= yield %>
  </body>
</html>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>